import mongoose from "mongoose";
import dotenv from "dotenv";
import Content from "../models/Content.js";
import Menu from "../models/Menu.js";
import dns from "dns";

dns.setServers(["1.1.1.1", "8.8.8.8"]);
dotenv.config();

// ─────────────────────────────────────────────────────────────────
// All images from https://picsum.photos — free, no key, no login.
// poster_url  → 300 × 450   (portrait  — movie cards)
// banner_url  → 1280 × 720  (landscape — hero banners)
// ─────────────────────────────────────────────────────────────────

const menuData = [
  { name: "Home", slug: "home", contentType: "all", order: 1, isActive: true },
  { name: "Movies", slug: "movies", contentType: "movie", order: 2, isActive: true },
  { name: "Shows", slug: "shows", contentType: "show", order: 3, isActive: true },
  { name: "Originals", slug: "originals", contentType: "original", order: 4, isActive: true },
];

const contentData = [

  // ╔══════════════════════════════════════════╗
  // ║           TELUGU  MOVIES                 ║
  // ╚══════════════════════════════════════════╝
  {
    title: "Pushpa: The Rise",
    description: "A laborer rises through the ranks of a red sandalwood smuggling syndicate, encountering enemies and corruption at every step.",
    poster_url: "https://picsum.photos/id/10/300/450",
    banner_url: "https://picsum.photos/id/110/1280/720",
    genre: ["Action", "Crime", "Drama"],
    release_year: 2021,
    type: "movie",
    language: "Telugu",
    rating: 8.0,
    popularity: 97,
    duration: "2h 59m",
    cast: ["Allu Arjun", "Rashmika Mandanna", "Fahadh Faasil"],
  },
  {
    title: "RRR",
    description: "A fictional story about two legendary revolutionaries and their journey before they began their fight for independence.",
    poster_url: "https://picsum.photos/id/20/300/450",
    banner_url: "https://picsum.photos/id/120/1280/720",
    genre: ["Action", "Drama", "Historical"],
    release_year: 2022,
    type: "movie",
    language: "Telugu",
    rating: 9.0,
    popularity: 100,
    duration: "3h 7m",
    cast: ["N.T. Rama Rao Jr.", "Ram Charan", "Alia Bhatt"],
  },
  {
    title: "Baahubali: The Conclusion",
    description: "When Shiva learns about his heritage, he begins a quest to avenge his mother's humiliation and reclaim his rightful throne.",
    poster_url: "https://picsum.photos/id/29/300/450",
    banner_url: "https://picsum.photos/id/129/1280/720",
    genre: ["Action", "Adventure", "Fantasy"],
    release_year: 2017,
    type: "movie",
    language: "Telugu",
    rating: 8.7,
    popularity: 95,
    duration: "2h 47m",
    cast: ["Prabhas", "Anushka Shetty", "Rana Daggubati"],
  },
  {
    title: "Ala Vaikunthapurramuloo",
    description: "A man raised by a rich family discovers that he was switched at birth, and decides to claim what is rightfully his.",
    poster_url: "https://picsum.photos/id/40/300/450",
    banner_url: "https://picsum.photos/id/140/1280/720",
    genre: ["Drama", "Action", "Comedy"],
    release_year: 2020,
    type: "movie",
    language: "Telugu",
    rating: 7.8,
    popularity: 88,
    duration: "2h 49m",
    cast: ["Allu Arjun", "Pooja Hegde", "Tabu"],
  },
  {
    title: "Dasara",
    description: "Set in the Singareni coal mines of Telangana, this gritty drama follows the transformation of a local gangster.",
    poster_url: "https://picsum.photos/id/50/300/450",
    banner_url: "https://picsum.photos/id/150/1280/720",
    genre: ["Action", "Drama"],
    release_year: 2023,
    type: "movie",
    language: "Telugu",
    rating: 7.5,
    popularity: 82,
    duration: "2h 55m",
    cast: ["Nani", "Keerthy Suresh", "Sree Leela"],
  },
  {
    title: "Baahubali: The Beginning",
    description: "A young man is raised by a tribe and seeks to uncover his true origins while falling in love with a warrior woman.",
    poster_url: "https://picsum.photos/id/11/300/450",
    banner_url: "https://picsum.photos/id/111/1280/720",
    genre: ["Action", "Adventure", "Fantasy"],
    release_year: 2015,
    type: "movie",
    language: "Telugu",
    rating: 8.5,
    popularity: 93,
    duration: "2h 38m",
    cast: ["Prabhas", "Tamannaah Bhatia", "Rana Daggubati"],
  },
  {
    title: "Magadheera",
    description: "A warrior and a princess from ancient times are reincarnated in the modern era, their fates intertwined once again.",
    poster_url: "https://picsum.photos/id/21/300/450",
    banner_url: "https://picsum.photos/id/121/1280/720",
    genre: ["Action", "Fantasy", "Romance"],
    release_year: 2009,
    type: "movie",
    language: "Telugu",
    rating: 8.3,
    popularity: 89,
    duration: "2h 37m",
    cast: ["Ram Charan", "Kajal Aggarwal", "Dev Gill"],
  },
  {
    title: "Arjun Reddy",
    description: "A short-tempered surgeon spirals into self-destruction after his college sweetheart is forced to marry someone else.",
    poster_url: "https://picsum.photos/id/30/300/450",
    banner_url: "https://picsum.photos/id/130/1280/720",
    genre: ["Drama", "Romance"],
    release_year: 2017,
    type: "movie",
    language: "Telugu",
    rating: 8.1,
    popularity: 86,
    duration: "3h 4m",
    cast: ["Vijay Deverakonda", "Shalini Pandey"],
  },
  {
    title: "Rangasthalam",
    description: "Set in 1985, a hearing-impaired man and his brother take on a corrupt panchayat president in their village.",
    poster_url: "https://picsum.photos/id/41/300/450",
    banner_url: "https://picsum.photos/id/141/1280/720",
    genre: ["Action", "Drama"],
    release_year: 2018,
    type: "movie",
    language: "Telugu",
    rating: 8.4,
    popularity: 91,
    duration: "2h 55m",
    cast: ["Ram Charan", "Samantha Ruth Prabhu", "Aadhi Pinisetty"],
  },
  {
    title: "Eega",
    description: "A man reincarnated as a housefly seeks revenge against the powerful businessman who murdered him.",
    poster_url: "https://picsum.photos/id/51/300/450",
    banner_url: "https://picsum.photos/id/151/1280/720",
    genre: ["Action", "Fantasy", "Thriller"],
    release_year: 2012,
    type: "movie",
    language: "Telugu",
    rating: 8.3,
    popularity: 85,
    duration: "2h 11m",
    cast: ["Nani", "Samantha Ruth Prabhu", "Sudeep"],
  },
  {
    title: "Vikram Vedha",
    description: "A tough police officer sets out to track down a dangerous gangster, but the lines between good and evil blur as he digs deeper.",
    poster_url: "https://picsum.photos/id/61/300/450",
    banner_url: "https://picsum.photos/id/161/1280/720",
    genre: ["Action", "Thriller", "Crime"],
    release_year: 2017,
    type: "movie",
    language: "Telugu",
    rating: 8.4,
    popularity: 87,
    duration: "2h 29m",
    cast: ["R. Madhavan", "Vijay Sethupathi", "Shraddha Srinath"],
  },
  {
    title: "Jersey",
    description: "A failed cricketer decides to make a comeback at 36 to fulfil his son's dream of getting a jersey from the Indian cricket team.",
    poster_url: "https://picsum.photos/id/71/300/450",
    banner_url: "https://picsum.photos/id/171/1280/720",
    genre: ["Drama", "Sports"],
    release_year: 2019,
    type: "movie",
    language: "Telugu",
    rating: 8.6,
    popularity: 88,
    duration: "2h 40m",
    cast: ["Nani", "Shraddha Srinath", "Sathyaraj"],
  },

  // ╔══════════════════════════════════════════╗
  // ║           HINDI  MOVIES                  ║
  // ╚══════════════════════════════════════════╝
  {
    title: "Pathaan",
    description: "An exiled spy returns to India to take on a deadly terrorist organisation threatening the nation.",
    poster_url: "https://picsum.photos/id/60/300/450",
    banner_url: "https://picsum.photos/id/160/1280/720",
    genre: ["Action", "Thriller"],
    release_year: 2023,
    type: "movie",
    language: "Hindi",
    rating: 7.2,
    popularity: 91,
    duration: "2h 26m",
    cast: ["Shah Rukh Khan", "Deepika Padukone", "John Abraham"],
  },
  {
    title: "Brahmastra Part One: Shiva",
    description: "A young DJ entangled in a world of ancient weapons and clandestine societies discovers his magical powers.",
    poster_url: "https://picsum.photos/id/70/300/450",
    banner_url: "https://picsum.photos/id/170/1280/720",
    genre: ["Fantasy", "Action", "Adventure"],
    release_year: 2022,
    type: "movie",
    language: "Hindi",
    rating: 6.8,
    popularity: 79,
    duration: "2h 54m",
    cast: ["Ranbir Kapoor", "Alia Bhatt", "Amitabh Bachchan"],
  },
  {
    title: "Jawan",
    description: "A prison warden recruits women to seek vengeance on corrupt industrialists, politicians, and executives.",
    poster_url: "https://picsum.photos/id/80/300/450",
    banner_url: "https://picsum.photos/id/180/1280/720",
    genre: ["Action", "Thriller"],
    release_year: 2023,
    type: "movie",
    language: "Hindi",
    rating: 7.6,
    popularity: 93,
    duration: "2h 49m",
    cast: ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi"],
  },
  {
    title: "Dangal",
    description: "A former wrestler trains his daughters to become world-class wrestlers against all social odds in rural India.",
    poster_url: "https://picsum.photos/id/12/300/450",
    banner_url: "https://picsum.photos/id/112/1280/720",
    genre: ["Drama", "Sports", "Biography"],
    release_year: 2016,
    type: "movie",
    language: "Hindi",
    rating: 8.4,
    popularity: 96,
    duration: "2h 41m",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra"],
  },
  {
    title: "3 Idiots",
    description: "Two friends search for their missing college buddy and recall the adventure-filled days they spent together at an engineering college.",
    poster_url: "https://picsum.photos/id/22/300/450",
    banner_url: "https://picsum.photos/id/122/1280/720",
    genre: ["Comedy", "Drama"],
    release_year: 2009,
    type: "movie",
    language: "Hindi",
    rating: 8.4,
    popularity: 95,
    duration: "2h 50m",
    cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi"],
  },
  {
    title: "Andhadhun",
    description: "A seemingly blind pianist accidentally becomes a witness to a murder and gets further entangled in a web of deceit.",
    poster_url: "https://picsum.photos/id/31/300/450",
    banner_url: "https://picsum.photos/id/131/1280/720",
    genre: ["Thriller", "Crime", "Drama"],
    release_year: 2018,
    type: "movie",
    language: "Hindi",
    rating: 8.3,
    popularity: 90,
    duration: "2h 19m",
    cast: ["Ayushmann Khurrana", "Tabu", "Radhika Apte"],
  },
  {
    title: "Gangs of Wasseypur",
    description: "A sprawling saga of coal mafia and power politics across multiple generations in the Dhanbad region of Jharkhand.",
    poster_url: "https://picsum.photos/id/42/300/450",
    banner_url: "https://picsum.photos/id/142/1280/720",
    genre: ["Action", "Crime", "Drama"],
    release_year: 2012,
    type: "movie",
    language: "Hindi",
    rating: 8.6,
    popularity: 88,
    duration: "2h 40m",
    cast: ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Richa Chadha"],
  },
  {
    title: "PK",
    description: "An alien stranded on Earth befriends a journalist and together they question blind religious rituals and superstitions.",
    poster_url: "https://picsum.photos/id/52/300/450",
    banner_url: "https://picsum.photos/id/152/1280/720",
    genre: ["Comedy", "Drama", "Satire"],
    release_year: 2014,
    type: "movie",
    language: "Hindi",
    rating: 8.1,
    popularity: 92,
    duration: "2h 33m",
    cast: ["Aamir Khan", "Anushka Sharma", "Sushant Singh Rajput"],
  },
  {
    title: "Tumbbad",
    description: "A greedy man discovers a secret treasure hidden by a mythical deity across multiple decades of his life.",
    poster_url: "https://picsum.photos/id/62/300/450",
    banner_url: "https://picsum.photos/id/162/1280/720",
    genre: ["Horror", "Fantasy", "Thriller"],
    release_year: 2018,
    type: "movie",
    language: "Hindi",
    rating: 8.4,
    popularity: 86,
    duration: "1h 44m",
    cast: ["Sohum Shah", "Jyoti Malshe", "Anita Date"],
  },

  // ╔══════════════════════════════════════════╗
  // ║           TELUGU  SHOWS                  ║
  // ╚══════════════════════════════════════════╝
  {
    title: "Aha Original: Inspector Rishi",
    description: "A stubborn inspector investigates supernatural killings deep in a forest reserve while confronting his own demons.",
    poster_url: "https://picsum.photos/id/90/300/450",
    banner_url: "https://picsum.photos/id/190/1280/720",
    genre: ["Crime", "Thriller", "Supernatural"],
    release_year: 2024,
    type: "show",
    language: "Telugu",
    rating: 8.5,
    popularity: 90,
    duration: "45m per episode",
    cast: ["Naveen Chandra", "Sunaina", "Avantika Vanidasu"],
  },
  {
    title: "Matsyagandha",
    description: "A gripping family drama set against the backdrop of the Godavari delta, exploring caste, power, and kinship.",
    poster_url: "https://picsum.photos/id/100/300/450",
    banner_url: "https://picsum.photos/id/200/1280/720",
    genre: ["Drama", "Family"],
    release_year: 2022,
    type: "show",
    language: "Telugu",
    rating: 7.9,
    popularity: 75,
    duration: "40m per episode",
    cast: ["Ananya", "Vennela Kishore", "Rohini"],
  },
  {
    title: "Unstoppable with NBK",
    description: "A celebrity talk show hosted by Balakrishna featuring candid conversations, games, and entertainment with top stars.",
    poster_url: "https://picsum.photos/id/111/300/450",
    banner_url: "https://picsum.photos/id/211/1280/720",
    genre: ["Talk Show", "Entertainment"],
    release_year: 2021,
    type: "show",
    language: "Telugu",
    rating: 7.4,
    popularity: 80,
    duration: "60m per episode",
    cast: ["Nandamuri Balakrishna"],
  },
  {
    title: "Maa Kathalu",
    description: "An anthology series showcasing emotionally rich short stories of everyday Telugu families and their untold struggles.",
    poster_url: "https://picsum.photos/id/13/300/450",
    banner_url: "https://picsum.photos/id/113/1280/720",
    genre: ["Drama", "Anthology"],
    release_year: 2022,
    type: "show",
    language: "Telugu",
    rating: 7.6,
    popularity: 70,
    duration: "30m per episode",
    cast: ["Various"],
  },
  {
    title: "Aha Crime Files",
    description: "A gripping crime investigation series featuring real-inspired cases solved by tenacious detectives across Andhra Pradesh.",
    poster_url: "https://picsum.photos/id/23/300/450",
    banner_url: "https://picsum.photos/id/123/1280/720",
    genre: ["Crime", "Drama", "Mystery"],
    release_year: 2023,
    type: "show",
    language: "Telugu",
    rating: 7.7,
    popularity: 73,
    duration: "40m per episode",
    cast: ["Sree Vishnu", "Priya Bhavani Shankar"],
  },

  // ╔══════════════════════════════════════════╗
  // ║           HINDI  SHOWS                   ║
  // ╚══════════════════════════════════════════╝
  {
    title: "Scam 1992",
    description: "The story of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.",
    poster_url: "https://picsum.photos/id/122/300/450",
    banner_url: "https://picsum.photos/id/222/1280/720",
    genre: ["Biography", "Crime", "Drama"],
    release_year: 2020,
    type: "show",
    language: "Hindi",
    rating: 9.3,
    popularity: 99,
    duration: "45m per episode",
    cast: ["Pratik Gandhi", "Shreya Dhanwanthary"],
  },
  {
    title: "Mirzapur",
    description: "Drugs, guns and crime rule the Purvanchal region as two brothers get dragged into the mafia underworld.",
    poster_url: "https://picsum.photos/id/133/300/450",
    banner_url: "https://picsum.photos/id/233/1280/720",
    genre: ["Crime", "Action", "Thriller"],
    release_year: 2018,
    type: "show",
    language: "Hindi",
    rating: 8.8,
    popularity: 96,
    duration: "55m per episode",
    cast: ["Ali Fazal", "Pankaj Tripathi", "Divyendu Sharma"],
  },
  {
    title: "Kota Factory",
    description: "A black-and-white slice-of-life drama following students preparing for the IIT-JEE entrance exam in the coaching hub of Kota.",
    poster_url: "https://picsum.photos/id/14/300/450",
    banner_url: "https://picsum.photos/id/114/1280/720",
    genre: ["Drama", "Slice of Life"],
    release_year: 2019,
    type: "show",
    language: "Hindi",
    rating: 9.0,
    popularity: 91,
    duration: "35m per episode",
    cast: ["Jitendra Kumar", "Mayur More", "Ranjan Raj"],
  },
  {
    title: "TVF Pitchers",
    description: "Four friends quit their corporate jobs to chase their dream of building a startup, facing funding woes and personal sacrifices.",
    poster_url: "https://picsum.photos/id/24/300/450",
    banner_url: "https://picsum.photos/id/124/1280/720",
    genre: ["Drama", "Comedy"],
    release_year: 2015,
    type: "show",
    language: "Hindi",
    rating: 9.1,
    popularity: 89,
    duration: "40m per episode",
    cast: ["Naveen Kasturia", "Arunabh Kumar", "Jitendra Kumar"],
  },
  {
    title: "Sacred Games",
    description: "A Mumbai police officer gets a mysterious tip from a gangster and embarks on a dark mission to save the city from destruction.",
    poster_url: "https://picsum.photos/id/32/300/450",
    banner_url: "https://picsum.photos/id/132/1280/720",
    genre: ["Crime", "Thriller", "Drama"],
    release_year: 2018,
    type: "show",
    language: "Hindi",
    rating: 8.7,
    popularity: 94,
    duration: "50m per episode",
    cast: ["Saif Ali Khan", "Nawazuddin Siddiqui", "Radhika Apte"],
  },

  // ╔══════════════════════════════════════════╗
  // ║         TELUGU  ORIGINALS                ║
  // ╚══════════════════════════════════════════╝
  {
    title: "Aha Champions: Season 1",
    description: "A reality fitness show in Telugu where celebrities and athletes compete in grueling physical challenges.",
    poster_url: "https://picsum.photos/id/144/300/450",
    banner_url: "https://picsum.photos/id/244/1280/720",
    genre: ["Reality", "Sports"],
    release_year: 2023,
    type: "original",
    language: "Telugu",
    rating: 7.1,
    popularity: 68,
    duration: "50m per episode",
    cast: ["Ravi Teja", "Raashi Khanna"],
  },
  {
    title: "Wild Dog",
    description: "Based on true events, an NIA officer hunts down a deadly terrorist cell executing bomb blasts across India.",
    poster_url: "https://picsum.photos/id/155/300/450",
    banner_url: "https://picsum.photos/id/255/1280/720",
    genre: ["Action", "Thriller"],
    release_year: 2021,
    type: "original",
    language: "Telugu",
    rating: 7.0,
    popularity: 72,
    duration: "1h 55m",
    cast: ["Nagarjuna", "Saiyami Kher", "Ali Reza"],
  },
  {
    title: "Colour Photo",
    description: "In 1990s Andhra, a love story unfolds between a lower-caste boy and a high-caste girl amid deep social barriers.",
    poster_url: "https://picsum.photos/id/166/300/450",
    banner_url: "https://picsum.photos/id/266/1280/720",
    genre: ["Drama", "Romance"],
    release_year: 2020,
    type: "original",
    language: "Telugu",
    rating: 8.2,
    popularity: 85,
    duration: "2h 12m",
    cast: ["Suhas", "Chandini Chowdary"],
  },
  {
    title: "Bheemla Nayak",
    description: "A principled police constable and an arrogant ex-army officer clash in an intense battle of egos that spirals into tragedy.",
    poster_url: "https://picsum.photos/id/15/300/450",
    banner_url: "https://picsum.photos/id/115/1280/720",
    genre: ["Action", "Drama"],
    release_year: 2022,
    type: "original",
    language: "Telugu",
    rating: 7.8,
    popularity: 83,
    duration: "2h 40m",
    cast: ["Pawan Kalyan", "Rana Daggubati", "Nithya Menen"],
  },
  {
    title: "Sarkaru Vaari Paata",
    description: "A loan recovery agent falls in love and unknowingly ends up confronting the very people who ruined his family years ago.",
    poster_url: "https://picsum.photos/id/25/300/450",
    banner_url: "https://picsum.photos/id/125/1280/720",
    genre: ["Action", "Romance", "Drama"],
    release_year: 2022,
    type: "original",
    language: "Telugu",
    rating: 7.3,
    popularity: 78,
    duration: "2h 34m",
    cast: ["Mahesh Babu", "Keerthy Suresh"],
  },
  {
    title: "Ante Sundaraniki",
    description: "A Hindu boy and a Christian girl fall in love but must navigate the resistance of their conservative religious families.",
    poster_url: "https://picsum.photos/id/33/300/450",
    banner_url: "https://picsum.photos/id/133/1280/720",
    genre: ["Comedy", "Romance"],
    release_year: 2022,
    type: "original",
    language: "Telugu",
    rating: 7.6,
    popularity: 80,
    duration: "2h 25m",
    cast: ["Nani", "Nazriya Nazim"],
  },

  // ╔══════════════════════════════════════════╗
  // ║          HINDI  ORIGINALS                ║
  // ╚══════════════════════════════════════════╝
  {
    title: "The Family Man",
    description: "A middle-class intelligence officer tries to protect the nation from threats while keeping his family life intact.",
    poster_url: "https://picsum.photos/id/177/300/450",
    banner_url: "https://picsum.photos/id/277/1280/720",
    genre: ["Action", "Drama", "Thriller"],
    release_year: 2019,
    type: "original",
    language: "Hindi",
    rating: 9.1,
    popularity: 98,
    duration: "50m per episode",
    cast: ["Manoj Bajpayee", "Priyamani", "Samantha"],
  },
  {
    title: "Panchayat",
    description: "A graduate reluctantly takes up a government posting in rural Uttar Pradesh and slowly learns to appreciate life there.",
    poster_url: "https://picsum.photos/id/188/300/450",
    banner_url: "https://picsum.photos/id/288/1280/720",
    genre: ["Comedy", "Drama"],
    release_year: 2020,
    type: "original",
    language: "Hindi",
    rating: 9.0,
    popularity: 94,
    duration: "30m per episode",
    cast: ["Jitendra Kumar", "Raghubir Yadav", "Neena Gupta"],
  },
  {
    title: "Delhi Crime",
    description: "Based on a true story, a Delhi Police team investigates one of the most horrific crimes in India's history.",
    poster_url: "https://picsum.photos/id/199/300/450",
    banner_url: "https://picsum.photos/id/299/1280/720",
    genre: ["Crime", "Drama", "Thriller"],
    release_year: 2019,
    type: "original",
    language: "Hindi",
    rating: 8.5,
    popularity: 87,
    duration: "45m per episode",
    cast: ["Shefali Shah", "Rasika Dugal", "Adil Hussain"],
  },
  {
    title: "Aspirants",
    description: "Three friends in Delhi dream of cracking the UPSC exam while navigating friendships that define their lives.",
    poster_url: "https://picsum.photos/id/210/300/450",
    banner_url: "https://picsum.photos/id/310/1280/720",
    genre: ["Drama", "Slice of Life"],
    release_year: 2021,
    type: "original",
    language: "Hindi",
    rating: 9.2,
    popularity: 92,
    duration: "25m per episode",
    cast: ["Naveen Kasturia", "Sunny Hinduja", "Shivankit Singh Parihar"],
  },
  {
    title: "Jamtara: Sabka Number Aayega",
    description: "Small-town youngsters running a phishing scam empire attract the attention of an ambitious politician and a relentless cop.",
    poster_url: "https://picsum.photos/id/43/300/450",
    banner_url: "https://picsum.photos/id/143/1280/720",
    genre: ["Crime", "Drama", "Thriller"],
    release_year: 2020,
    type: "original",
    language: "Hindi",
    rating: 7.9,
    popularity: 83,
    duration: "35m per episode",
    cast: ["Amit Sial", "Monika Panwar", "Sparsh Shrivastava"],
  },
  {
    title: "Hostel Daze",
    description: "A group of engineering students navigate the chaotic, hilarious, and unforgettable experience of life in a college hostel.",
    poster_url: "https://picsum.photos/id/53/300/450",
    banner_url: "https://picsum.photos/id/153/1280/720",
    genre: ["Comedy", "Drama"],
    release_year: 2019,
    type: "original",
    language: "Hindi",
    rating: 8.6,
    popularity: 85,
    duration: "25m per episode",
    cast: ["Nikhil Vijay", "Shubham Gaur", "Adarsh Gourav"],
  },
  {
    title: "Rocket Boys",
    description: "The extraordinary lives of India's pioneering space scientists Vikram Sarabhai and Homi J. Bhabha as they build a nation's scientific identity.",
    poster_url: "https://picsum.photos/id/63/300/450",
    banner_url: "https://picsum.photos/id/163/1280/720",
    genre: ["Biography", "Drama", "Historical"],
    release_year: 2022,
    type: "original",
    language: "Hindi",
    rating: 8.9,
    popularity: 90,
    duration: "45m per episode",
    cast: ["Jim Sarbh", "Ishwak Singh", "Regina Cassandra"],
  },
  {
    title: "Breathe: Into the Shadows",
    description: "A psychiatrist is forced to commit a series of murders when his daughter is kidnapped by a shadowy figure demanding impossible tasks.",
    poster_url: "https://picsum.photos/id/73/300/450",
    banner_url: "https://picsum.photos/id/173/1280/720",
    genre: ["Thriller", "Crime", "Drama"],
    release_year: 2020,
    type: "original",
    language: "Hindi",
    rating: 7.8,
    popularity: 82,
    duration: "50m per episode",
    cast: ["Abhishek Bachchan", "Amit Sadh", "Nithya Menen"],
  },
];

// ─────────────────────────────────────────────
// Seed Function
// ─────────────────────────────────────────────
const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("📦  Connected to MongoDB...");

    await Content.deleteMany({});
    await Menu.deleteMany({});
    console.log("🗑️   Cleared existing Content and Menu collections.");

    await Menu.insertMany(menuData);
    console.log(`📋  Inserted ${menuData.length} menu items.`);

    await Content.insertMany(contentData);
    console.log(`🎬  Inserted ${contentData.length} content items.`);

    console.log("✅  Seeding complete!");
  } catch (error) {
    console.error("❌  Seeding failed:", error.message);
  } finally {
    await mongoose.disconnect();
    console.log("🔌  Disconnected from MongoDB.");
  }
};

seedDB();